// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8q3G_GoDUe_7e2XFIMdtsOBSKWQcdIcs',
    appId: '1:554268367169:web:f19103623cf311332369c0',
    messagingSenderId: '554268367169',
    projectId: 'tasha-36c1e',
    authDomain: 'tasha-36c1e.firebaseapp.com',
    storageBucket: 'tasha-36c1e.firebasestorage.app',
    measurementId: 'G-J9TP71LV7C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlxnq_XFeRVvCu_PFq4ha5U6A8z6xMfTs',
    appId: '1:554268367169:android:5e428e86843bf7442369c0',
    messagingSenderId: '554268367169',
    projectId: 'tasha-36c1e',
    storageBucket: 'tasha-36c1e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLavW1RW73gVz8CdrDDYdJEmNVO1fAKKE',
    appId: '1:554268367169:ios:c8bb93d40d74f0062369c0',
    messagingSenderId: '554268367169',
    projectId: 'tasha-36c1e',
    storageBucket: 'tasha-36c1e.firebasestorage.app',
    iosBundleId: 'com.example.tashaapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLavW1RW73gVz8CdrDDYdJEmNVO1fAKKE',
    appId: '1:554268367169:ios:c8bb93d40d74f0062369c0',
    messagingSenderId: '554268367169',
    projectId: 'tasha-36c1e',
    storageBucket: 'tasha-36c1e.firebasestorage.app',
    iosBundleId: 'com.example.tashaapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA8q3G_GoDUe_7e2XFIMdtsOBSKWQcdIcs',
    appId: '1:554268367169:web:75fcd92411098dbc2369c0',
    messagingSenderId: '554268367169',
    projectId: 'tasha-36c1e',
    authDomain: 'tasha-36c1e.firebaseapp.com',
    storageBucket: 'tasha-36c1e.firebasestorage.app',
    measurementId: 'G-Z4BJ7GE6NN',
  );
}
